spring:
  application:
    name: discovery-service

server:
  port: 9080

eureka:
  instance:
    hostname: travel-agency-discovery.herokuapp.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
